spring:
  application:
    name: gateway-service
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://service-registry:1111/eureka
server:
  port:
    8080