spring:
  application:
    name: user-service
  data:
    rest:
      basePath: /api
eureka:
  instance:
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

server:
  port: 8081
